### ISSUE TITLE
use console.log

### ISSUE THREAD

**Issue by aheckmann** [sam-github/node-debuglog#3]
Any reason this isn't using console.log? I

**Comment by sam-github** [comment]
Because its a polyfill (aka "cut-n-paste") of a node v0.11 API for node v0.10, so it does as node does:

https://github.com/joyent/node/blob/master/lib/util.js#L107

**Comment by aheckmann** [comment]
thanks. following up there

On Thursday, May 15, 2014, Sam Roberts notifications@github.com wrote:

> Closed #3 https://github.com/sam-github/node-debuglog/issues/3.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sam-github/node-debuglog/issues/3#event-121715559
> .

## 

Aaron
@aaronheckmann https://twitter.com/#!/aaronheckmann
soundcloud.com/ajhecky
github.com/aheckmann

**Comment by sam-github** [comment]
On Thu, May 15, 2014 at 5:48 PM, Aaron Heckmann notifications@github.comwrote:

> thanks. following up there

stderr is a decent place, btw, it ensures your debug output does not
intermingle with actual/non-debug output.

ideally, it would be configurable, but that's a lot of overhead.

recall that this is only for node internal use, if you want stdout debug
logging, use visionmedia/debug. make sure to use recent ones, it used to
debug to stderr, too, but has now switched to stdout.

**Comment by aheckmann** [comment]
right thats why i asked. i've been using `debug` forever and noticed the
difference. thanks

On Fri, May 16, 2014 at 9:44 AM, Sam Roberts notifications@github.comwrote:

> On Thu, May 15, 2014 at 5:48 PM, Aaron Heckmann <notifications@github.com
> 
> > wrote:
> > 
> > thanks. following up there
> 
> stderr is a decent place, btw, it ensures your debug output does not
> intermingle with actual/non-debug output.
> 
> ideally, it would be configurable, but that's a lot of overhead.
> 
> recall that this is only for node internal use, if you want stdout debug
> logging, use visionmedia/debug. make sure to use recent ones, it used to
> debug to stderr, too, but has now switched to stdout.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sam-github/node-debuglog/issues/3#issuecomment-43353067
> .

## 

Aaron
@aaronheckmann https://twitter.com/#!/aaronheckmann
soundcloud.com/ajhecky
github.com/aheckmann

**Comment by sam-github** [comment]
On Fri, May 16, 2014 at 9:50 AM, Aaron Heckmann
notifications@github.com wrote:

> right thats why i asked. i've been using `debug` forever and noticed the
> difference. thanks

Two months is forever? ;-)

https://github.com/visionmedia/debug/commit/491eea3b33cb52da73a78b4f65a58b4f778ee197

**Comment by aheckmann** [comment]
? I've been using https://www.npmjs.org/package/debug

On Fri, May 16, 2014 at 10:37 AM, Sam Roberts notifications@github.comwrote:

> On Fri, May 16, 2014 at 9:50 AM, Aaron Heckmann
> notifications@github.com wrote:
> 
> > right thats why i asked. i've been using `debug` forever and noticed the
> > difference. thanks
> 
> Two months is forever? ;-)
> 
> https://github.com/visionmedia/debug/commit/491eea3b33cb52da73a78b4f65a58b4f778ee197
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sam-github/node-debuglog/issues/3#issuecomment-43358584
> .

## 

Aaron
@aaronheckmann https://twitter.com/#!/aaronheckmann
soundcloud.com/ajhecky
github.com/aheckmann

**Comment by sam-github** [comment]
On Fri, May 16, 2014 at 10:39 AM, Aaron Heckmann
notifications@github.com wrote:

> ? I've been using https://www.npmjs.org/package/debug

Exactly. My link was to it's git repo. TJ changed to stdout two months ago.

**Comment by aheckmann** [comment]
"forever" means I've been using debug forever not that its been console.log
forever. Not sure what this conversation is about at this point.

On Fri, May 16, 2014 at 10:41 AM, Sam Roberts notifications@github.comwrote:

> On Fri, May 16, 2014 at 10:39 AM, Aaron Heckmann
> notifications@github.com wrote:
> 
> > ? I've been using https://www.npmjs.org/package/debug
> 
> Exactly. My link was to it's git repo. TJ changed to stdout two months
> ago.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sam-github/node-debuglog/issues/3#issuecomment-43359083
> .

## 

Aaron
@aaronheckmann https://twitter.com/#!/aaronheckmann
soundcloud.com/ajhecky
github.com/aheckmann

**Comment by sam-github** [comment]
I had the impression you were looking for information about why this code uses stderr, as node does and TJ's debug module did until two months ago, and was trying to be helpful, sorry if that info is not of use to you. Cheers.

**Comment by aheckmann** [comment]
yeah i was and your answer was helpful. thanks!

**Comment by sam-github** [comment]
np, you are welcome.
