### ISSUE TITLE
Consider supporting browsers

### ISSUE THREAD

**Issue by Raynos** [sam-github/node-debuglog#4]
Instead of reading `process.env` consider reading `window.NODE_DEBUG` or `document.location.search` for `?NODE_DEBUG=phrase`

This way we can use this in browser modules and people can turn the debuglog on with a global variable or a query string

**Comment by sam-github** [comment]
Consider using  https://github.com/visionmedia/debug

This is a node 0.10 polyfill for a node 0.11 API, its not really intended to be generally useful, unlike visonmedia's debug library.

That said, if you have an unobtrusive patch that doesn't break on node, feel free to PR.
